[workspace]
members = ["cegla", "cegla-cgi", "cegla-fcgi", "cegla-scgi", "examples", "tokio-cegla", "vibeio-cegla"]
resolver = "2"

[workspace.dependencies]
cegla = "=0.2.2"
cegla-cgi = "=0.2.2"
cegla-fcgi = "=0.2.2"
cegla-scgi = "=0.2.2"
tokio-cegla = "=0.2.2"
shiba = "0.1.1"

[patch.crates-io]
cegla = { path = "./cegla" }
cegla-cgi = { path = "./cegla-cgi" }
cegla-fcgi = { path = "./cegla-fcgi" }
cegla-scgi = { path = "./cegla-scgi" }
tokio-cegla = { path = "./tokio-cegla" }

[workspace.metadata.cargo-shear]
ignored = ["shiba"]
