[package]
name = "cegla-fcgi"
version = "0.2.1"
edition = "2021"
authors = ["Dorian Niemiec <dorian@ferron.sh>"]
description = "High-level FastCGI implementation for Rust"
license = "MIT"
readme = "../README.md"
keywords = ["http", "cgi", "fastcgi"]
categories = ["web-programming", "network-programming"]
documentation = "https://docs.rs/cegla-fcgi"
repository = "https://github.com/ferronweb/cegla"

[dependencies]
async-channel = "2.5.0"
cegla = { workspace = true }
futures-util = { version = "0.3.32", features = ["sink"] }
hashlink = "0.11.0"
http = "1.4.0"
http-body = "1.0.1"
http-body-util = "0.1.3"
oneshot = { version = "0.2.1", optional = true, features = ["async"] }
parking_lot = "0.12.5"
pin-project-lite = "0.2.17"
tokio = { version = "1.49.0", features = ["rt", "macros"] }
tokio-util = { version = "0.7.18", features = ["io", "codec"] }

[dev-dependencies]
shiba = { workspace = true }

[features]
default = ["client"]
client = ["cegla/client", "oneshot", "tokio/sync"]
server = ["cegla/server"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
